version: "3.8"
   
services:
  nginx:
    restart: always
    image: nginx:latest
    expose:
      - 8080
    ports:
          - "80:8080"
    volumes:
            - ./logs:/var/www/mediasoft/logs
            - ./nginx:/etc/nginx/conf.d
    depends_on:
            - web
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
  web:
    restart: always
    build: .
    volumes:
      - .:/var/www/mediasoft
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: "gunicorn -c gunicorn.py mediasoft.wsgi"
    depends_on:
      - db